# Generated by Django 5.1.6 on 2025-02-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_ticket_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_fix',
            field=models.CharField(blank=True, choices=[('restart_ehr', 'Restart the EHR server, clear caches, and check network load.'), ('verify_devices', 'Verify device configurations and network connectivity; update firmware if needed.'), ('review_logs', 'Review system logs, reschedule maintenance, and test system responsiveness.'), ('optimize_wifi', 'Optimize router placement, update firmware, and check for interference.'), ('investigate_security', 'Investigate login logs, enforce strong authentication, and update security protocols.'), ('restart_printer', 'Restart the printer, verify network settings, and check for driver updates.'), ('upgrade_network', 'Analyze network bandwidth usage and consider hardware upgrades or traffic shaping.'), ('rollback_update', 'Rollback the update, apply patches after thorough testing, and document changes.'), ('reconfigure_network', 'Reconfigure network segments, test connectivity, and consult network logs.'), ('restart_vpn', 'Restart VPN services, review remote access policies, and verify firewall rules.')], help_text='Select the fix implemented by the admin.', max_length=50, null=True),
        ),
    ]
