# Generated by Django 5.1.6 on 2025-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
