# Generated by Django 5.1.6 on 2025-02-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Level 1 (Lowest)'), (2, 'Level 2 (Medium)'), (3, 'Level 3 (Highest)')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Medical', 'Medical'), ('Administrative', 'Administrative'), ('Support/Ancillary', 'Support/Ancillary')], max_length=50)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.prioritylevel')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tickets/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.department')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.prioritylevel')),
            ],
        ),
    ]
