# Generated by Django 5.1.6 on 2025-02-19 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Internal code for the department (e.g., 'Medical').", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name for the department (e.g., 'Medical Departments').", max_length=100)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Internal code for the sub-department (e.g., 'ED').", max_length=50)),
                ('name', models.CharField(help_text="Display name for the sub-department (e.g., 'Emergency Department (ED)').", max_length=100)),
                ('priority', models.CharField(choices=[('3', 'Level 3 (Highest)'), ('2', 'Level 2 (Medium)'), ('1', 'Level 1 (Lowest)')], help_text='Priority level for this sub-department based on the color-coded system.', max_length=1)),
                ('department', models.ForeignKey(help_text='The parent department for this sub-department.', on_delete=django.db.models.deletion.CASCADE, related_name='subdepartments', to='ticketing.department')),
            ],
            options={
                'verbose_name': 'Sub-Department',
                'verbose_name_plural': 'Sub-Departments',
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the submitter.', max_length=100)),
                ('email', models.EmailField(help_text='Email of the submitter.', max_length=254)),
                ('phone', models.CharField(help_text='Phone number of the submitter.', max_length=20)),
                ('issue', models.TextField(help_text='Describe the issue or request.')),
                ('screenshot', models.ImageField(blank=True, help_text='Optional screenshot.', null=True, upload_to='ticket_screenshots/')),
                ('priority', models.CharField(choices=[('3', 'Level 3 (Highest)'), ('2', 'Level 2 (Medium)'), ('1', 'Level 1 (Lowest)')], editable=False, help_text='Priority level auto-assigned from the sub-department.', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(help_text='Select the parent department.', on_delete=django.db.models.deletion.PROTECT, to='ticketing.department')),
                ('sub_department', models.ForeignKey(help_text='Select the sub-department corresponding to the chosen department.', on_delete=django.db.models.deletion.PROTECT, to='ticketing.subdepartment')),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
